# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20160302_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graphs.Scenario'),
        ),
    ]
