# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_student_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='graphs.Activity'),
        ),
    ]
