# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0007_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
