# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0010_auto_20160322_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 23, 8, 50, 11, 76438, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('quiz', 'Quiz'), ('link', 'Link')], max_length=4),
        ),
    ]
