# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0011_auto_20160323_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='path',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_activity',
            field=models.IntegerField(default=0),
        ),
    ]
