# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0014_auto_20160406_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='set',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
