# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0015_activity_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='set',
        ),
    ]
