# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0016_remove_activity_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSpent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.Activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.Student')),
            ],
        ),
    ]
