# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0017_timespent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSpent',
            new_name='TimeLog',
        ),
        migrations.AlterUniqueTogether(
            name='timelog',
            unique_together=set([('student', 'activity')]),
        ),
    ]
