# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0018_auto_20160413_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
