# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0020_auto_20160420_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='given_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphs.Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='graphs.Choice'),
        ),
    ]
