# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0021_auto_20160420_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='raphaelJson',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='source',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timelog',
            unique_together=set([]),
        ),
    ]
