# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0022_auto_20160501_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='source',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
