# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0025_auto_20160504_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='graphs.Choice'),
            preserve_default=False,
        ),
    ]
