# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0031_auto_20160504_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='activity',
            field=models.ManyToManyField(blank=True, to='graphs.Activity'),
        ),
    ]
