# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0036_auto_20160511_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='group',
        ),
    ]
