# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0040_auto_20160531_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='creator',
        ),
        migrations.AddField(
            model_name='scenario',
            name='email_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
    ]
