# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0042_auto_20160601_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
